name: capi
description: Project CAPI


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  url_launcher: ^6.1.5
  timeline_tile: ^2.0.0
  flutter_zoom_drawer: 3.0.0
  get: 4.6.5
  shared_preferences: ^2.0.5
  percent_indicator: ^4.0.1
  flutter_rounded_date_picker: 3.0.1
  babstrap_settings_screen: ^0.1.3
  fluttertoast: ^8.0.9
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.3


flutter_native_splash:
  color: "#FAFAFA"
  image: assets/images/launch_image.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/Profile_Page/
    - assets/quiz/
    - assets/RoadMap/



  fonts:

    - family: Comfort
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
